# Generated by Django 4.2 on 2023-05-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
