# Generated by Django 4.2 on 2023-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_user', '0002_delete_category_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(default='', max_length=40)),
                ('p_num', models.CharField(max_length=30)),
                ('p_description', models.TextField()),
                ('p_author', models.CharField(max_length=300)),
            ],
        ),
    ]
